-- CreateEnum
CREATE TYPE "UserTrackingStatus" AS ENUM ('REGISTERED', 'ACTIVATED', 'PROFILE_PENDING', 'PROFILE_COMPLETED');

-- CreateEnum
CREATE TYPE "TestTrackingStatus" AS ENUM ('TEST_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_COMPLETED', 'RESULT_EVALUATED');

-- AlterTable
ALTER TABLE "Exam" ADD COLUMN     "statusTracking" "TestTrackingStatus" NOT NULL DEFAULT 'TEST_STARTED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "statusTracking" "UserTrackingStatus" NOT NULL DEFAULT 'REGISTERED';
