## Redis configuration for UAT
auth:
  enabled: true
  password: 'kh4eyAH97hFimV4SVg1zDQ@@'

## Architecture
architecture: standalone

## Master configuration (lighter for uat)
master:
  persistence:
    enabled: true
    storageClass: 'standard-rwo'
    size: 2Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m

  ## Security context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

## Redis configuration (simpler for uat)
redis:
  configuration: |-
    # Redis uat configuration
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    save ""  # Disable persistence snapshots for uat
    tcp-keepalive 60

## Monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: false

## Network Policy
networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    enabled: true
    from:
      - namespaceSelector:
          matchLabels:
            name: devplus-aicp-uat
