image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: '7.0.15-debian-12-r6'
  pullPolicy: IfNotPresent
  pullSecrets: []

auth:
  enabled: true
  existingSecret: aicp-api-env
  existingSecretPasswordKey: REDIS_PASSWORD

architecture: standalone

master:
  persistence:
    enabled: true
    storageClass: 'standard-rwo'
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    annotations: {}

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
    fsGroupChangePolicy: Always

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  pdb:
    enabled: true
    minAvailable: 1

  ## Node affinity and tolerations
  affinity: {}
  nodeSelector: {}
  tolerations: []

  ## Pod annotations
  podAnnotations: {}
  podLabels: {}

redis:
  configuration: |-
    # Redis production configuration
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    tcp-keepalive 300
    timeout 0
    databases 16
    # Security
    protected-mode yes
    # Performance
    tcp-backlog 511
    # Logging
    loglevel notice

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    enabled: true
    from:
      - namespaceSelector:
          matchLabels:
            name: devplus-aicp
service:
  type: ClusterIP
  ports:
    redis: 6379
  annotations: {}
  sessionAffinity: None

tls:
  enabled: false
  authClients: true
  autoGenerated: false
