## Redis configuration for Development
image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 7.2.3-debian-11-r1
  pullPolicy: IfNotPresent
  pullSecrets: []

auth:
  enabled: true
  existingSecret: aicp-api-env
  existingSecretPasswordKey: REDIS_PASSWORD

## Architecture
architecture: standalone

## Master configuration (lighter for dev)
master:
  persistence:
    enabled: true
    storageClass: 'standard-rwo'
    size: 2Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m

  ## Security context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

## Redis configuration (simpler for dev)
redis:
  configuration: |-
    # Redis development configuration
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    save ""  # Disable persistence snapshots for dev
    tcp-keepalive 60

## Monitoring
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

## Network Policy
networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    enabled: true
    from:
      - namespaceSelector:
          matchLabels:
            name: devplus-aicp-dev
