# 1. Build
FROM node:16.18.0-alpine
# Set working directory
WORKDIR /app
#
COPY package*.json /app/
COPY yarn*.lock /app/

# Same as npm install
RUN yarn install

RUN apk update && apk upgrade && apk add --no-cache bash git openjpeg-tools

COPY . .

RUN yarn build

CMD [ "node", "dist/main.js" ]
