postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: '16.3.0-debian-12-r6'

  auth:
    enablePostgresUser: true
    existingSecret: aicp-api-env
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
    username: postgres
    database: aicp

  primary:
    persistence:
      enabled: true
      size: 8Gi

    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 4Gi
        cpu: 2

# Add service configuration for template
service:
  port: 5432
  type: ClusterIP

backup:
  enabled: true
  cronjob:
    schedule: '0 2 * * *'
    historyLimit: 7
    restartPolicy: OnFailure

  persistence:
    enabled: true
    storageClass: 'standard-rwo'
    size: 100Gi
    accessModes:
      - ReadWriteOnce
