auth:
  enablePostgresUser: true
  postgresPassword: +c2QWpz6KnPOt045zQoDeA++
  username: 'postgres'
  password: +c2QWpz6KnPOt045zQoDeA++
  database: 'aicp_dev'

primary:
  persistence:
    enabled: true
    storageClass: 'standard-rwo'
    size: 5Gi
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

backup:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: false # Usually no Prometheus in dev

networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    enabled: true
    from:
      - namespaceSelector:
          matchLabels:
            name: devplus-aicp-dev
