postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: '16.3.0-debian-12-r6'
    pullPolicy: IfNotPresent

  auth:
    enablePostgresUser: true
    existingSecret: aicp-api-env
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
    username: postgres
    database: aicp_dev

  primary:
    persistence:
      enabled: true
      storageClass: 'standard-rwo'
      size: 5Gi
      accessModes:
        - ReadWriteOnce

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m

    securityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001

    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

service:
  port: 5432
  type: ClusterIP

backup:
  enabled: false

networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    enabled: true
    from:
      - namespaceSelector:
          matchLabels:
            name: devplus-aicp-dev
