apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aicp-api
spec:
  serviceName: aicp-api
  replicas: 3
  selector:
    matchLabels:
      app: aicp-api
  template:
    metadata:
      labels:
        app: aicp-api
      annotations:
        checksum/config: '{{ .Values.configChecksum }}'
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroupChangePolicy: 'OnRootMismatch'
      initContainers:
        - name: db-migration
          image: asia-southeast1-docker.pkg.dev/enspara/aicp/aicp-api:0.2.15
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking database connection..."
              until nc -z postgres-aicp-postgresql.devplus-aicp-dev.svc.cluster.local 5432; do
                echo "Waiting for database to be ready..."
                sleep 5
              done
              echo "Database connected successfully"
              echo "Running migrations..."
              yarn prisma migrate deploy
              echo "Migration completed successfully"

              echo "Running seed (will skip if data exists)..."
              yarn db:seed:k8s || echo "Seed failed or skipped"
              echo "Init container completed"
          envFrom:
            - secretRef:
                name: aicp-api-env
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsGroup: 1000
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
      containers:
        - name: aicp-api
          image: asia-southeast1-docker.pkg.dev/enspara/aicp/aicp-api:0.2.15
          ports:
            - name: http
              containerPort: 6002
              protocol: TCP
          envFrom:
            - secretRef:
                name: aicp-api-env
          volumeMounts:
            - name: storage-volume
              mountPath: /app/server/storage
            - name: firebase-service-key
              mountPath: /app/secrets
              readOnly: true
            - name: google-service-key
              mountPath: /app/etc
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
            - name: cache-volume
              mountPath: /app/.cache
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsGroup: 1000
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: 1.5Gi
              cpu: '1.5'
            limits:
              memory: 3Gi
              cpu: '3'
      volumes:
        - name: firebase-service-key
          secret:
            secretName: firebase-service-key
        - name: google-service-key
          secret:
            secretName: google-service-key
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: standard-rwo
        resources:
          requests:
            storage: 20Gi
